version: '3.8'

services:
  web:
    build: .
    user: "0:0"  # Run as root to access OpenVPN system files
    network_mode: "host"
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /etc/openvpn:/etc/openvpn
      - /var/log/openvpn:/var/log/openvpn
      - /var/www/templates:/var/www/templates