services:
  web:
    build: .
    user: "0:0"  # Run as root to access OpenVPN system files
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/openvpn:/etc/openvpn
      - /var/log/openvpn:/var/log/openvpn
      - /var/www/templates:/var/www/templates
      - /data/lomtechvpnaccess/ssh/keys:/app/ssh:ro
    environment:
      - HOST_SSH_KEY=/app/ssh/id_host_access